package raycluster

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"sigs.k8s.io/yaml"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	"github.com/opendatahub-io/odh-cli/pkg/util/client"
	"github.com/opendatahub-io/odh-cli/pkg/util/iostreams"
)

// PreUpgrade runs pre-upgrade: preflight checks and backup of RayClusters to outputDir (rhoai-2.x and rhoai-3.x subdirs).
// If outputDir is empty, returns error (caller should prompt or use default).
func PreUpgrade(
	ctx context.Context,
	c client.Client,
	outputDir string,
	clusterName string,
	namespace string,
	checks []PreflightCheck,
	io iostreams.Interface,
) ([]string, error) {
	if outputDir == "" {
		return nil, errors.New("output directory is required")
	}

	if err := reportPreflightChecks(checks, io); err != nil {
		return nil, err
	}

	rhoai2Dir, rhoai3Dir, err := ensureBackupDirs(outputDir, io)
	if err != nil {
		return nil, err
	}

	clusters, err := GetClusters(ctx, c, clusterName, namespace)
	if err != nil {
		return nil, err
	}
	if len(clusters) == 0 {
		io.Errorf("No RayClusters found to backup")

		return nil, nil
	}

	logBackupScope(clusterName, namespace, len(clusters), io)

	var savedFiles []string
	for _, rc := range clusters {
		f, err := backupCluster(rc, rhoai2Dir, rhoai3Dir, io)
		if err != nil {
			return savedFiles, err
		}
		if f != "" {
			savedFiles = append(savedFiles, f)
		}
	}

	return savedFiles, nil
}

func reportPreflightChecks(checks []PreflightCheck, io iostreams.Interface) error {
	io.Errorf("Running pre-upgrade checks...")
	io.Errorf("------------------------------------------------------------")

	for _, chk := range checks {
		status := "[OK]"
		if !chk.Passed {
			status = "[FAIL]"
		}
		io.Errorf("  %s %s: %s", status, chk.Name, chk.Message)
		if len(chk.Details) > 0 && !chk.Passed {
			for _, d := range chk.Details {
				io.Errorf("       - %s", d)
			}
		}
		if !chk.Passed && chk.Required && chk.Help != "" {
			io.Errorf("       %s", chk.Help)
		}
	}

	io.Errorf("------------------------------------------------------------")

	hasRequiredFailure := false
	allPassed := true
	for _, chk := range checks {
		if !chk.Passed {
			allPassed = false
			if chk.Required {
				hasRequiredFailure = true
			}
		}
	}

	if hasRequiredFailure {
		io.Errorf("")
		io.Errorf("Pre-upgrade checks failed. Please resolve the issues above before proceeding with the RHOAI upgrade.")

		return errors.New("pre-upgrade checks failed")
	}
	if allPassed {
		io.Errorf("All pre-upgrade checks passed.")
	} else {
		io.Errorf("Pre-upgrade checks completed with warnings.")
	}
	io.Errorf("")

	return nil
}

func ensureBackupDirs(outputDir string, io iostreams.Interface) (rhoai2Dir, rhoai3Dir string, err error) { //nolint:nonamedreturns // named for clarity per confusing-results
	outputDirExisted := true
	if _, err := os.Stat(outputDir); os.IsNotExist(err) {
		outputDirExisted = false
	}
	if err := os.MkdirAll(outputDir, dirPermissions); err != nil {
		return "", "", fmt.Errorf("create backup directory: %w", err)
	}
	if !outputDirExisted {
		io.Errorf("Created backup directory: %s", outputDir)
	}

	rhoai2Dir = filepath.Join(outputDir, BackupSubdirRHOAI2x)
	rhoai3Dir = filepath.Join(outputDir, BackupSubdirRHOAI3x)
	for _, d := range []string{rhoai2Dir, rhoai3Dir} {
		if err := os.MkdirAll(d, dirPermissions); err != nil {
			return "", "", fmt.Errorf("create backup subdirectory %s: %w", d, err)
		}
	}

	return rhoai2Dir, rhoai3Dir, nil
}

func logBackupScope(clusterName, namespace string, count int, io iostreams.Interface) {
	scopeMsg := "all clusters across all namespaces"
	if clusterName != "" && namespace != "" {
		scopeMsg = fmt.Sprintf("cluster '%s' in namespace '%s'", clusterName, namespace)
	} else if namespace != "" {
		scopeMsg = fmt.Sprintf("all clusters in namespace '%s'", namespace)
	}
	io.Errorf("Backing up %d RayCluster(s) (%s)", count, scopeMsg)
	io.Errorf("")
}

func backupCluster(rc *unstructured.Unstructured, rhoai2Dir, rhoai3Dir string, io iostreams.Interface) (string, error) {
	name := rc.GetName()
	ns := rc.GetNamespace()
	if ns == "" {
		ns = DefaultNamespace
	}

	filename := "raycluster-" + name + "-" + ns + yamlExt
	f2x := filepath.Join(rhoai2Dir, filename)
	f3x := filepath.Join(rhoai3Dir, filename)

	obj2x := rc.DeepCopy()
	RemoveAutogeneratedFields(obj2x.Object)
	if err := writeUnstructuredToFile(obj2x, f2x); err != nil {
		return "", fmt.Errorf("backing up %s/%s (RHOAI 2.x): %w", ns, name, err)
	}

	obj3x := rc.DeepCopy()
	RemoveAutogeneratedFields(obj3x.Object)
	ProcessRayClusterYAML(obj3x)
	if err := writeUnstructuredToFile(obj3x, f3x); err != nil {
		_ = os.Remove(f2x)

		return "", fmt.Errorf("backing up %s/%s (RHOAI 3.x): %w", ns, name, err)
	}

	io.Errorf("  Backed up: %s (namespace: %s)", name, ns)

	return f3x, nil
}

func writeUnstructuredToFile(u *unstructured.Unstructured, path string) error {
	data, err := yaml.Marshal(u.Object)
	if err != nil {
		return fmt.Errorf("marshaling YAML: %w", err)
	}

	if err = os.WriteFile(path, data, filePermissions); err != nil {
		return fmt.Errorf("writing file %s: %w", path, err)
	}

	return nil
}
