package raycluster

import (
	"os"
	"time"
)

// SecureNetworkAnnotation marks a RayCluster as migrated to secure trusted network (RHOAI 3.x).
const SecureNetworkAnnotation = "odh.ray.io/secure-trusted-network"

// FieldManager is the server-side apply identifier (kept for compatibility with codeflare-sdk).
const FieldManager = "codeflare-sdk"

// DefaultNamespace is the Kubernetes default namespace name.
const DefaultNamespace = "default"

// DefaultBackupDir is the backup directory used when not specified.
const DefaultBackupDir = "./raycluster-backups"

const (
	// BackupSubdirRHOAI2x is the subdirectory name for RHOAI 2.x backups.
	BackupSubdirRHOAI2x = "rhoai-2.x"
	// BackupSubdirRHOAI3x is the subdirectory name for RHOAI 3.x backups.
	BackupSubdirRHOAI3x = "rhoai-3.x"
)

// DefaultRouteTimeout is the default time to wait for a cluster's Gateway API route to become available.
const DefaultRouteTimeout = 2 * time.Minute

// stateReady is the RayCluster status value indicating all pods are healthy.
const stateReady = "ready"

const (
	yamlExt = ".yaml"
	ymlExt  = ".yml"
)

const (
	dirPermissions  os.FileMode = 0o750
	filePermissions os.FileMode = 0o600
)

// TLSEnvVars contains TLS-related environment variable names to remove or detect.
var TLSEnvVars = map[string]struct{}{ //nolint:gochecknoglobals // read-only lookup table
	"RAY_USE_TLS":         {},
	"RAY_TLS_SERVER_CERT": {},
	"RAY_TLS_SERVER_KEY":  {},
	"RAY_TLS_CA_CERT":     {},
}

// VolumesToRemove contains volume names to remove (TLS/OAuth).
var VolumesToRemove = map[string]struct{}{ //nolint:gochecknoglobals // read-only lookup table
	"ca-vol":           {},
	"proxy-tls-secret": {},
	"server-cert":      {},
}

// VolumeMountsToRemove contains volume mount names to remove from containers.
var VolumeMountsToRemove = map[string]struct{}{ //nolint:gochecknoglobals // read-only lookup table
	"ca-vol":      {},
	"server-cert": {},
}

// ContainersToRemove contains sidecar container names to remove (e.g. oauth-proxy).
var ContainersToRemove = map[string]struct{}{ //nolint:gochecknoglobals // read-only lookup table
	"oauth-proxy": {},
}

// CodeFlareInitContainers contains initContainer names to remove (cert generation).
var CodeFlareInitContainers = map[string]struct{}{ //nolint:gochecknoglobals // read-only lookup table
	"create-cert": {},
}

// KueueAnnotationsToStrip contains annotation keys to strip from backup/restore. Kueue sets these on the
// Workload and pod templates; old values from a deleted cluster cause admission
// conflicts when applying a backup (value1=old workload name, value2=new).
var KueueAnnotationsToStrip = map[string]struct{}{ //nolint:gochecknoglobals // read-only lookup table
	"kueue.x-k8s.io/workload": {},
	"kueue.x-k8s.io/podset":   {},
}

// AutogeneratedFields contains metadata keys to strip from backup/replace.
var AutogeneratedFields = map[string]struct{}{ //nolint:gochecknoglobals // read-only lookup table
	"creationTimestamp":             {},
	"resourceVersion":               {},
	"uid":                           {},
	"selfLink":                      {},
	"managedFields":                 {},
	"finalizers":                    {},
	"generation":                    {},
	"status":                        {},
	"workload.codeflare.dev/user":   {},
	"workload.codeflare.dev/userid": {},
	"podSetInfos":                   {},
}
