package raycluster_test

import (
	"testing"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	"github.com/opendatahub-io/odh-cli/pkg/migrate/raycluster"

	. "github.com/onsi/gomega"
)

// --- helpers ---

func newRayCluster(name, ns string, specFn func(map[string]any)) *unstructured.Unstructured {
	spec := map[string]any{}
	if specFn != nil {
		specFn(spec)
	}
	rc := &unstructured.Unstructured{
		Object: map[string]any{
			"apiVersion": "ray.io/v1",
			"kind":       "RayCluster",
			"metadata": map[string]any{
				"name":      name,
				"namespace": ns,
			},
			"spec": spec,
		},
	}

	return rc
}

func withTLSHead(spec map[string]any) {
	spec["headGroupSpec"] = map[string]any{
		"enableIngress": true,
		"template": map[string]any{
			"spec": map[string]any{
				"serviceAccountName": "my-cluster-oauth-proxy-sa",
				"containers": []any{
					map[string]any{
						"name":  "ray-head",
						"image": "ray:latest",
						"env": []any{
							map[string]any{"name": "RAY_USE_TLS", "value": "1"},
							map[string]any{"name": "RAY_TLS_SERVER_CERT", "value": "/etc/certs/tls.crt"},
							map[string]any{"name": "RAY_TLS_SERVER_KEY", "value": "/etc/certs/tls.key"},
							map[string]any{"name": "RAY_TLS_CA_CERT", "value": "/etc/ca/ca.crt"},
							map[string]any{"name": "MY_APP_ENV", "value": "production"},
						},
						"volumeMounts": []any{
							map[string]any{"name": "ca-vol", "mountPath": "/etc/ca"},
							map[string]any{"name": "server-cert", "mountPath": "/etc/certs"},
							map[string]any{"name": "data-vol", "mountPath": "/data"},
						},
					},
					map[string]any{
						"name":  "oauth-proxy",
						"image": "oauth-proxy:latest",
					},
				},
				"initContainers": []any{
					map[string]any{
						"name":  "create-cert",
						"image": "cert-gen:latest",
					},
				},
				"volumes": []any{
					map[string]any{"name": "ca-vol", "secret": map[string]any{"secretName": "ca-cert"}},
					map[string]any{"name": "server-cert", "secret": map[string]any{"secretName": "server-cert"}},
					map[string]any{"name": "proxy-tls-secret", "secret": map[string]any{"secretName": "proxy-tls"}},
					map[string]any{"name": "data-vol", "emptyDir": map[string]any{}},
				},
			},
		},
	}
}

func withTLSWorker(spec map[string]any) {
	spec["workerGroupSpecs"] = []any{
		map[string]any{
			"replicas": int64(2),
			"template": map[string]any{
				"spec": map[string]any{
					"containers": []any{
						map[string]any{
							"name":  "ray-worker",
							"image": "ray:latest",
							"env": []any{
								map[string]any{"name": "RAY_USE_TLS", "value": "1"},
								map[string]any{"name": "RAY_TLS_SERVER_CERT", "value": "/etc/certs/tls.crt"},
								map[string]any{"name": "RAY_TLS_SERVER_KEY", "value": "/etc/certs/tls.key"},
								map[string]any{"name": "RAY_TLS_CA_CERT", "value": "/etc/ca/ca.crt"},
							},
							"volumeMounts": []any{
								map[string]any{"name": "ca-vol", "mountPath": "/etc/ca"},
								map[string]any{"name": "server-cert", "mountPath": "/etc/certs"},
							},
						},
					},
					"initContainers": []any{
						map[string]any{
							"name":  "create-cert",
							"image": "cert-gen:latest",
						},
					},
					"volumes": []any{
						map[string]any{"name": "ca-vol", "secret": map[string]any{"secretName": "ca-cert"}},
						map[string]any{"name": "server-cert", "secret": map[string]any{"secretName": "server-cert"}},
					},
				},
			},
		},
	}
}

func withAnnotations(rc *unstructured.Unstructured, anns map[string]string) {
	rc.SetAnnotations(anns)
}

// --- RemoveAutogeneratedFields ---

func TestRemoveAutogeneratedFields_TopLevel(t *testing.T) {
	g := NewWithT(t)

	obj := map[string]any{
		"apiVersion":        "ray.io/v1",
		"kind":              "RayCluster",
		"creationTimestamp": "2024-01-01T00:00:00Z",
		"resourceVersion":   "12345",
		"uid":               "abc-123",
		"selfLink":          "/api/v1/rayclusters/foo",
		"managedFields":     []any{map[string]any{"manager": "kubectl"}},
		"finalizers":        []any{"foregroundDeletion"},
		"generation":        int64(3),
		"status":            map[string]any{"state": "ready"},
		"metadata":          map[string]any{"name": "my-cluster"},
	}

	raycluster.RemoveAutogeneratedFields(obj)

	g.Expect(obj).ToNot(HaveKey("creationTimestamp"))
	g.Expect(obj).ToNot(HaveKey("resourceVersion"))
	g.Expect(obj).ToNot(HaveKey("uid"))
	g.Expect(obj).ToNot(HaveKey("selfLink"))
	g.Expect(obj).ToNot(HaveKey("managedFields"))
	g.Expect(obj).ToNot(HaveKey("finalizers"))
	g.Expect(obj).ToNot(HaveKey("generation"))
	g.Expect(obj).ToNot(HaveKey("status"))
	g.Expect(obj).To(HaveKey("apiVersion"))
	g.Expect(obj).To(HaveKey("kind"))
	g.Expect(obj).To(HaveKey("metadata"))
}

func TestRemoveAutogeneratedFields_Nested(t *testing.T) {
	g := NewWithT(t)

	obj := map[string]any{
		"metadata": map[string]any{
			"name":              "my-cluster",
			"creationTimestamp": "2024-01-01T00:00:00Z",
			"resourceVersion":   "12345",
			"uid":               "abc-123",
			"managedFields":     []any{map[string]any{"manager": "kubectl"}},
		},
		"spec": map[string]any{
			"headGroupSpec": map[string]any{
				"enableIngress": true,
			},
		},
	}

	raycluster.RemoveAutogeneratedFields(obj)

	meta, _ := obj["metadata"].(map[string]any)
	g.Expect(meta).To(HaveKey("name"))
	g.Expect(meta).ToNot(HaveKey("creationTimestamp"))
	g.Expect(meta).ToNot(HaveKey("resourceVersion"))
	g.Expect(meta).ToNot(HaveKey("uid"))
	g.Expect(meta).ToNot(HaveKey("managedFields"))

	spec, _ := obj["spec"].(map[string]any)
	g.Expect(spec).To(HaveKey("headGroupSpec"))
}

func TestRemoveAutogeneratedFields_ArrayOfMaps(t *testing.T) {
	g := NewWithT(t)

	obj := map[string]any{
		"items": []any{
			map[string]any{
				"name":              "item-1",
				"creationTimestamp": "2024-01-01",
				"uid":               "xyz",
			},
			map[string]any{
				"name":          "item-2",
				"managedFields": []any{},
			},
		},
	}

	raycluster.RemoveAutogeneratedFields(obj)

	items, _ := obj["items"].([]any)
	item1, _ := items[0].(map[string]any)
	g.Expect(item1).To(HaveKey("name"))
	g.Expect(item1).ToNot(HaveKey("creationTimestamp"))
	g.Expect(item1).ToNot(HaveKey("uid"))

	item2, _ := items[1].(map[string]any)
	g.Expect(item2).To(HaveKey("name"))
	g.Expect(item2).ToNot(HaveKey("managedFields"))
}

func TestRemoveAutogeneratedFields_CodeFlareAnnotations(t *testing.T) {
	g := NewWithT(t)

	obj := map[string]any{
		"metadata": map[string]any{
			"name": "my-cluster",
			"annotations": map[string]any{
				"workload.codeflare.dev/user":   "admin",
				"workload.codeflare.dev/userid": "1234",
				"other-annotation":              "keep",
			},
		},
	}

	raycluster.RemoveAutogeneratedFields(obj)

	meta, _ := obj["metadata"].(map[string]any)
	anns, _ := meta["annotations"].(map[string]any)
	g.Expect(anns).ToNot(HaveKey("workload.codeflare.dev/user"))
	g.Expect(anns).ToNot(HaveKey("workload.codeflare.dev/userid"))
	g.Expect(anns).To(HaveKeyWithValue("other-annotation", "keep"))
}

func TestRemoveAutogeneratedFields_EmptyObject(t *testing.T) {
	g := NewWithT(t)

	obj := map[string]any{}
	raycluster.RemoveAutogeneratedFields(obj)
	g.Expect(obj).To(BeEmpty())
}

// --- RemoveKueueWorkloadAnnotations ---

func TestRemoveKueueWorkloadAnnotations_ClusterLevel(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", nil)
	rc.SetAnnotations(map[string]string{
		"kueue.x-k8s.io/workload": "wl-abc",
		"kueue.x-k8s.io/podset":   "podset-1",
		"other/annotation":        "keep-me",
	})

	raycluster.RemoveKueueWorkloadAnnotations(rc)

	anns := rc.GetAnnotations()
	g.Expect(anns).ToNot(HaveKey("kueue.x-k8s.io/workload"))
	g.Expect(anns).ToNot(HaveKey("kueue.x-k8s.io/podset"))
	g.Expect(anns).To(HaveKeyWithValue("other/annotation", "keep-me"))
}

func TestRemoveKueueWorkloadAnnotations_HeadGroupTemplate(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", func(spec map[string]any) {
		spec["headGroupSpec"] = map[string]any{
			"template": map[string]any{
				"metadata": map[string]any{
					"annotations": map[string]any{
						"kueue.x-k8s.io/workload": "wl-head",
						"kueue.x-k8s.io/podset":   "head-podset",
						"app/label":               "keep",
					},
				},
			},
		}
	})

	raycluster.RemoveKueueWorkloadAnnotations(rc)

	ann, _, _ := unstructured.NestedMap(rc.Object, "spec", "headGroupSpec", "template", "metadata", "annotations")
	g.Expect(ann).ToNot(HaveKey("kueue.x-k8s.io/workload"))
	g.Expect(ann).ToNot(HaveKey("kueue.x-k8s.io/podset"))
	g.Expect(ann).To(HaveKeyWithValue("app/label", "keep"))
}

func TestRemoveKueueWorkloadAnnotations_WorkerGroupTemplate(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", func(spec map[string]any) {
		spec["workerGroupSpecs"] = []any{
			map[string]any{
				"template": map[string]any{
					"metadata": map[string]any{
						"annotations": map[string]any{
							"kueue.x-k8s.io/workload": "wl-worker",
							"kueue.x-k8s.io/podset":   "worker-podset",
							"custom/ann":              "keep",
						},
					},
				},
			},
		}
	})

	raycluster.RemoveKueueWorkloadAnnotations(rc)

	workers, _, _ := unstructured.NestedSlice(rc.Object, "spec", "workerGroupSpecs")
	g.Expect(workers).To(HaveLen(1))
	w0, _ := workers[0].(map[string]any)
	ann, _, _ := unstructured.NestedMap(w0, "template", "metadata", "annotations")
	g.Expect(ann).ToNot(HaveKey("kueue.x-k8s.io/workload"))
	g.Expect(ann).ToNot(HaveKey("kueue.x-k8s.io/podset"))
	g.Expect(ann).To(HaveKeyWithValue("custom/ann", "keep"))
}

func TestRemoveKueueWorkloadAnnotations_NoAnnotations(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", nil)
	raycluster.RemoveKueueWorkloadAnnotations(rc)
	g.Expect(rc.GetAnnotations()).To(BeNil())
}

// --- HasTLSOAuthComponents ---

func TestHasTLSOAuthComponents_EmptySpec(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", nil)
	has, components := raycluster.HasTLSOAuthComponents(rc)
	g.Expect(has).To(BeFalse())
	g.Expect(components).To(BeEmpty())
}

func TestHasTLSOAuthComponents_OAuthProxy(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", func(spec map[string]any) {
		spec["headGroupSpec"] = map[string]any{
			"template": map[string]any{
				"spec": map[string]any{
					"containers": []any{
						map[string]any{"name": "ray-head"},
						map[string]any{"name": "oauth-proxy"},
					},
				},
			},
		}
	})

	has, components := raycluster.HasTLSOAuthComponents(rc)
	g.Expect(has).To(BeTrue())
	g.Expect(components).To(ContainElement(ContainSubstring("oauth-proxy")))
}

func TestHasTLSOAuthComponents_TLSEnvVars(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", func(spec map[string]any) {
		spec["headGroupSpec"] = map[string]any{
			"template": map[string]any{
				"spec": map[string]any{
					"containers": []any{
						map[string]any{
							"name": "ray-head",
							"env": []any{
								map[string]any{"name": "RAY_USE_TLS", "value": "1"},
							},
						},
					},
				},
			},
		}
	})

	has, components := raycluster.HasTLSOAuthComponents(rc)
	g.Expect(has).To(BeTrue())
	g.Expect(components).To(ContainElement(ContainSubstring("TLS env var")))
}

func TestHasTLSOAuthComponents_InitContainers(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", func(spec map[string]any) {
		spec["headGroupSpec"] = map[string]any{
			"template": map[string]any{
				"spec": map[string]any{
					"initContainers": []any{
						map[string]any{"name": "create-cert", "image": "cert-gen:latest"},
					},
				},
			},
		}
	})

	has, components := raycluster.HasTLSOAuthComponents(rc)
	g.Expect(has).To(BeTrue())
	g.Expect(components).To(ContainElement(ContainSubstring("create-cert")))
}

func TestHasTLSOAuthComponents_TLSVolumes(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", func(spec map[string]any) {
		spec["headGroupSpec"] = map[string]any{
			"template": map[string]any{
				"spec": map[string]any{
					"volumes": []any{
						map[string]any{"name": "ca-vol"},
						map[string]any{"name": "server-cert"},
						map[string]any{"name": "proxy-tls-secret"},
					},
				},
			},
		}
	})

	has, components := raycluster.HasTLSOAuthComponents(rc)
	g.Expect(has).To(BeTrue())
	g.Expect(components).To(HaveLen(3))
}

func TestHasTLSOAuthComponents_EnableIngress(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", func(spec map[string]any) {
		spec["headGroupSpec"] = map[string]any{
			"enableIngress": true,
		}
	})

	has, components := raycluster.HasTLSOAuthComponents(rc)
	g.Expect(has).To(BeTrue())
	g.Expect(components).To(ContainElement(ContainSubstring("enableIngress")))
}

func TestHasTLSOAuthComponents_WorkerGroup(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", func(spec map[string]any) {
		spec["workerGroupSpecs"] = []any{
			map[string]any{
				"template": map[string]any{
					"spec": map[string]any{
						"containers": []any{
							map[string]any{
								"name": "ray-worker",
								"env": []any{
									map[string]any{"name": "RAY_USE_TLS", "value": "1"},
								},
							},
						},
					},
				},
			},
		}
	})

	has, components := raycluster.HasTLSOAuthComponents(rc)
	g.Expect(has).To(BeTrue())
	g.Expect(components).To(ContainElement(ContainSubstring("worker[0]")))
}

func TestHasTLSOAuthComponents_FullCluster(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", func(spec map[string]any) {
		withTLSHead(spec)
		withTLSWorker(spec)
	})

	has, components := raycluster.HasTLSOAuthComponents(rc)
	g.Expect(has).To(BeTrue())
	g.Expect(len(components)).To(BeNumerically(">=", 5))
}

func TestHasTLSOAuthComponents_NoTLSComponents(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", func(spec map[string]any) {
		spec["headGroupSpec"] = map[string]any{
			"template": map[string]any{
				"spec": map[string]any{
					"containers": []any{
						map[string]any{
							"name":  "ray-head",
							"image": "ray:latest",
							"env": []any{
								map[string]any{"name": "MY_APP_ENV", "value": "prod"},
							},
						},
					},
					"volumes": []any{
						map[string]any{"name": "data-vol", "emptyDir": map[string]any{}},
					},
				},
			},
		}
	})

	has, components := raycluster.HasTLSOAuthComponents(rc)
	g.Expect(has).To(BeFalse())
	g.Expect(components).To(BeEmpty())
}

// --- ProcessRayClusterYAML ---

func TestProcessRayClusterYAML_FullCleanup(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", withTLSHead)
	raycluster.ProcessRayClusterYAML(rc)

	head, _, _ := unstructured.NestedMap(rc.Object, "spec", "headGroupSpec")

	// enableIngress should be false
	enableIngress, _, _ := unstructured.NestedBool(head, "enableIngress")
	g.Expect(enableIngress).To(BeFalse())

	// oauth-proxy container should be removed, ray-head should remain
	containers, _, _ := unstructured.NestedSlice(head, "template", "spec", "containers")
	g.Expect(containers).To(HaveLen(1))
	c0, _ := containers[0].(map[string]any)
	g.Expect(c0["name"]).To(Equal("ray-head"))

	// TLS env vars should be removed from ray-head, MY_APP_ENV should remain
	envs, _, _ := unstructured.NestedSlice(c0, "env")
	g.Expect(envs).To(HaveLen(1))
	e0, _ := envs[0].(map[string]any)
	g.Expect(e0["name"]).To(Equal("MY_APP_ENV"))

	// TLS volume mounts should be removed, data-vol should remain
	mounts, _, _ := unstructured.NestedSlice(c0, "volumeMounts")
	g.Expect(mounts).To(HaveLen(1))
	m0, _ := mounts[0].(map[string]any)
	g.Expect(m0["name"]).To(Equal("data-vol"))

	// create-cert init container should be removed entirely
	_, initExists, _ := unstructured.NestedSlice(head, "template", "spec", "initContainers")
	g.Expect(initExists).To(BeFalse())

	// serviceAccountName should be removed
	_, saExists, _ := unstructured.NestedString(head, "template", "spec", "serviceAccountName")
	g.Expect(saExists).To(BeFalse())

	// TLS volumes removed, data-vol should remain
	vols, _, _ := unstructured.NestedSlice(head, "template", "spec", "volumes")
	g.Expect(vols).To(HaveLen(1))
	v0, _ := vols[0].(map[string]any)
	g.Expect(v0["name"]).To(Equal("data-vol"))
}

func TestProcessRayClusterYAML_WorkerCleanup(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", withTLSWorker)
	raycluster.ProcessRayClusterYAML(rc)

	workers, _, _ := unstructured.NestedSlice(rc.Object, "spec", "workerGroupSpecs")
	g.Expect(workers).To(HaveLen(1))
	w0, _ := workers[0].(map[string]any)
	podSpec, _, _ := unstructured.NestedMap(w0, "template", "spec")

	// TLS env vars removed from worker container
	containers, _, _ := unstructured.NestedSlice(podSpec, "containers")
	g.Expect(containers).To(HaveLen(1))
	c0, _ := containers[0].(map[string]any)
	_, envExists, _ := unstructured.NestedSlice(c0, "env")
	g.Expect(envExists).To(BeFalse())

	// create-cert init container removed
	_, initExists, _ := unstructured.NestedSlice(podSpec, "initContainers")
	g.Expect(initExists).To(BeFalse())

	// TLS volumes removed
	vols, _, _ := unstructured.NestedSlice(podSpec, "volumes")
	g.Expect(vols).To(BeEmpty())
}

func TestProcessRayClusterYAML_EmptySpec(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", nil)
	raycluster.ProcessRayClusterYAML(rc)

	spec, ok, _ := unstructured.NestedMap(rc.Object, "spec")
	g.Expect(ok).To(BeTrue())
	g.Expect(spec).To(BeEmpty())
}

func TestProcessRayClusterYAML_PreservesNonTLSContainers(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", func(spec map[string]any) {
		spec["headGroupSpec"] = map[string]any{
			"template": map[string]any{
				"spec": map[string]any{
					"containers": []any{
						map[string]any{
							"name":  "ray-head",
							"image": "ray:latest",
							"env": []any{
								map[string]any{"name": "MY_ENV", "value": "val"},
							},
						},
						map[string]any{
							"name":  "sidecar",
							"image": "sidecar:latest",
						},
					},
				},
			},
		}
	})

	raycluster.ProcessRayClusterYAML(rc)

	containers, _, _ := unstructured.NestedSlice(rc.Object, "spec", "headGroupSpec", "template", "spec", "containers")
	g.Expect(containers).To(HaveLen(2))
}

func TestProcessRayClusterYAML_PreservesServiceAccountNameWithoutOAuthProxy(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", func(spec map[string]any) {
		spec["headGroupSpec"] = map[string]any{
			"template": map[string]any{
				"spec": map[string]any{
					"serviceAccountName": "my-custom-sa",
					"containers": []any{
						map[string]any{
							"name":  "ray-head",
							"image": "ray:latest",
						},
					},
				},
			},
		}
	})

	raycluster.ProcessRayClusterYAML(rc)

	sa, ok, _ := unstructured.NestedString(rc.Object, "spec", "headGroupSpec", "template", "spec", "serviceAccountName")
	g.Expect(ok).To(BeTrue())
	g.Expect(sa).To(Equal("my-custom-sa"))
}

func TestProcessRayClusterYAML_Idempotent(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", func(spec map[string]any) {
		withTLSHead(spec)
		withTLSWorker(spec)
	})

	raycluster.ProcessRayClusterYAML(rc)
	firstPass := rc.DeepCopy()

	raycluster.ProcessRayClusterYAML(rc)

	g.Expect(rc.Object).To(Equal(firstPass.Object))
}

// --- IsClusterMigrated ---

func TestIsClusterMigrated_AlreadyMigrated(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", func(spec map[string]any) {
		spec["headGroupSpec"] = map[string]any{
			"template": map[string]any{
				"spec": map[string]any{
					"containers": []any{
						map[string]any{"name": "ray-head", "image": "ray:latest"},
					},
				},
			},
		}
	})
	withAnnotations(rc, map[string]string{
		raycluster.SecureNetworkAnnotation: "true",
	})

	migrated, reason := raycluster.IsClusterMigrated(rc)
	g.Expect(migrated).To(BeTrue())
	g.Expect(reason).To(ContainSubstring("Already migrated"))
}

func TestIsClusterMigrated_PartiallyMigrated(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", withTLSHead)
	withAnnotations(rc, map[string]string{
		raycluster.SecureNetworkAnnotation: "true",
	})

	migrated, reason := raycluster.IsClusterMigrated(rc)
	g.Expect(migrated).To(BeFalse())
	g.Expect(reason).To(ContainSubstring("Partially migrated"))
}

func TestIsClusterMigrated_NeedsAnnotationOnly(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", func(spec map[string]any) {
		spec["headGroupSpec"] = map[string]any{
			"template": map[string]any{
				"spec": map[string]any{
					"containers": []any{
						map[string]any{"name": "ray-head"},
					},
				},
			},
		}
	})

	migrated, reason := raycluster.IsClusterMigrated(rc)
	g.Expect(migrated).To(BeFalse())
	g.Expect(reason).To(ContainSubstring("Needs annotation only"))
}

func TestIsClusterMigrated_NeedsFullMigration(t *testing.T) {
	g := NewWithT(t)

	rc := newRayCluster("test", "default", withTLSHead)

	migrated, reason := raycluster.IsClusterMigrated(rc)
	g.Expect(migrated).To(BeFalse())
	g.Expect(reason).To(ContainSubstring("Needs migration"))
	g.Expect(reason).To(ContainSubstring("has:"))
}
